### ISSUE TITLE
Hide Select Image Button when image is selected and shouldAllowMultiple is false

### ISSUE THREAD

**Issue by luckycreationsindia** [tshedor/flutter_image_form_field#10]
Hi,

Is there a way to hide button when image is selected and shouldAllowMultiple is false? This feature is really required. If there is only single image there's no need to show select image button when image is already selected.

I tried count parameter in button builder but it won't listen to that after image is selected

**Comment by tshedor** [comment]
@luckycreationsindia This isn't available right now, but it sounds like a great idea. PRs are open!

**Comment by tshedor** [comment]
Closing due to no response
